338747: Adding Open API spec for Economic Operators
DEFRA/stw-api-descriptions pull request #4
Opened 2024-04-15 14:16 UTC by sean-treanor

2024-04-15 14:17 UTC, sean-treanor commented on common.yaml
> +    Unauthorized:
This file will be removed in a rebase once the branch I copied it from is merged.

2024-04-16 08:50 UTC, reece-bennett approved these changes

2024-04-16 08:58 UTC, reece-bennett requested changes

2024-04-16 08:58 UTC, reece-bennett commented on economic-operator.yaml
> +          type: string
The dates can have `format: date` as well

2024-04-16 08:58 UTC, reece-bennett commented on economic-operator.yaml
> +          type: string
`type: boolean`

2024-04-16 08:58 UTC, reece-bennett commented on economic-operator.yaml
> +          type: string
The timestamps can have `format: date-time`

2024-04-16 08:58 UTC, reece-bennett commented on economic-operator.yaml
> +                  $ref: "#/components/schemas/EconomicOperator"
Add the error responses too:

```yaml
400:
  $ref: "./common.yaml#/components/responses/BadRequest"
401:
  $ref: "./common.yaml#/components/responses/Unauthorized"
403:
  $ref: "./common.yaml#/components/responses/Forbidden"
```

2024-04-16 09:33 UTC, reece-bennett submitted a review, later dismissed

2024-04-16 14:19 UTC, kamilmkainos submitted a review, later dismissed

2024-04-16 14:34 UTC, reece-bennett approved these changes, later dismissed

2024-04-16 15:04 UTC, kamilmkainos approved these changes, later dismissed

2024-04-17 12:58 UTC, kamilmkainos approved these changes

2024-04-17 12:59 UTC, reece-bennett approved these changes

2024-04-17 12:59 UTC, subash-lakshmikanthan approved these changes

2024-04-17 12:59 UTC, subash-lakshmikanthan commented on economic-operator.yaml
> +  /economic-operators/{id}:
can we please keep just only get all request ?

2024-04-19 11:50 UTC, merged